export const CREATE_NEW_TODO_LIST = 'CREATE_NEW_TODO_LIST';
export const DETELE_TODO_LIST = 'DETELE_TODO_LIST';
export const INIT_TODO_LIST = 'INIT_TODO_LIST';

export const CREATE_NEW_GROCERY_LIST = 'CREATE_NEW_GROCERY_LIST';
export const DETELE_GROCERY_LIST = 'DETELE_GROCERY_LIST';
export const INIT_GROCERY_LIST = 'INIT_GROCERY_LIST';

export const ENABLE_TUTORIALS = 'ENABLE_TUTORIALS';
export const DISABLE_TUTORIALS = 'DISABLE_TUTORIALS';
